"""First migration

Revision ID: 42957622ad6e
Revises: 
Create Date: 2023-04-12 10:37:22.838969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42957622ad6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('hostid', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hostid')
    )
    op.create_index(op.f('ix_host_hostid'), 'host', ['hostid'], unique=True)
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['host.hostid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_index(op.f('ix_host_hostid'), table_name='host')
    op.drop_table('host')
    # ### end Alembic commands ###
