"""First migration

Revision ID: 5632fa9f9237
Revises: 
Create Date: 2023-04-11 09:43:26.576341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5632fa9f9237'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('hostid', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hostid')
    )
    op.create_index(op.f('ix_host_hostid'), 'host', ['hostid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_hostid'), table_name='host')
    op.drop_table('host')
    # ### end Alembic commands ###
