"""fix

Revision ID: 6b41b32fff28
Revises: 904ea3e7fb85
Create Date: 2023-04-11 16:58:05.728553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b41b32fff28'
down_revision = '904ea3e7fb85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('host_id', sa.Integer(), nullable=False))
    op.drop_index('ix_item_id', table_name='item')
    op.drop_constraint('item_hostid_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'host', ['host_id'], ['hostid'])
    op.drop_column('item', 'id')
    op.drop_column('item', 'hostid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('hostid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_hostid_fkey', 'item', 'host', ['hostid'], ['hostid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_item_id', 'item', ['id'], unique=False)
    op.drop_column('item', 'host_id')
    # ### end Alembic commands ###
