"""Таблица мониторинга параметров

Revision ID: 904ea3e7fb85
Revises: 5632fa9f9237
Create Date: 2023-04-11 11:08:20.034208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904ea3e7fb85'
down_revision = '5632fa9f9237'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hostid'], ['host.hostid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hostid')
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
