"""fix column options

Revision ID: d671603961a9
Revises: d8661a8115c2
Create Date: 2024-08-21 14:32:20.590749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd671603961a9'
down_revision = 'd8661a8115c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_id'), table_name='item')
    # ### end Alembic commands ###
