"""fix hostid field

Revision ID: eaf473825ba2
Revises: 904ea3e7fb85
Create Date: 2023-04-11 13:49:58.080444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf473825ba2'
down_revision = '904ea3e7fb85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('host_id', sa.Integer(), nullable=False))
    op.drop_constraint('item_hostid_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'host', ['host_id'], ['hostid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('item', 'hostid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('hostid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_hostid_fkey', 'item', 'host', ['hostid'], ['hostid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('item', 'host_id')
    # ### end Alembic commands ###
