"""First migration

Revision ID: f1f8dbfd102d
Revises: 
Create Date: 2023-04-21 10:20:18.919719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f8dbfd102d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('host_id')
    )
    op.create_index(op.f('ix_host_host_id'), 'host', ['host_id'], unique=True)
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['host.host_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_index(op.f('ix_host_host_id'), table_name='host')
    op.drop_table('host')
    # ### end Alembic commands ###
